### ISSUE TITLE
build error at libtool

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [coin-or/coinbrew#30] opened 2020-02-28 13:51 UTC
I failed to build ASL. The error message is "libtool: error :only absolute run-paths are allowed" Could you help me to solve this problem? Thanks a lot

**Comment by svigerske** [comment] 2020-02-28 14:31
That happens when the rpath flags passed to libtool does not specify an absolute path.
If you use coinbrew, then run with `--verbosity=4 --disable-silent-rules` to get more output and see what libtool command was failing. That may give an idea where the non-absolute rpath is coming from.

**Comment by Timbersaw-wangzw** [comment] 2020-02-28 14:45
> That happens when the rpath flags passed to libtool does not specify an absolute path.
> If you use coinbrew, then run with `--verbosity=4 --disable-silent-rules` to get more output and see what libtool command was failing. That may give an idea where the non-absolute rpath is coming from.
I run this code. I saw a warning "unreongnized options: --with-coin-instdir" . It seemed that i set a wrong path. and It resulted in the error which is "cannot create regular file". Could you tell me how to modify it?

**Comment by svigerske** [comment] 2020-02-28 14:47
You can ignore the warning "unrecognized options: --with-coin-instdir". That's harmless.

**Comment by Timbersaw-wangzw** [comment] 2020-02-29 04:32
> You can ignore the warning "unrecognized options: --with-coin-instdir". That's harmless.
Could you tell me how to modify the path of package installed？I tried to reconfigure it. and changed the "--prefix" variable but the path didn't changed.

**Comment by tkralphs** [comment] 2020-02-29 15:54
I'm not sure what you're asking. The new build system finds existing packages by `pkg-config`, so I think the answer to your question is to define (or add to) the environment variable `PKG_CONFIG_PATH`. I'm still not sure exactly what issue you're actually facing. We need more details.

**Comment by Timbersaw-wangzw** [comment] 2020-02-29 17:31
> I'm not sure what you're asking. The new build system finds existing packages by `pkg-config`, so I think the answer to your question is to define (or add to) the environment variable `PKG_CONFIG_PATH`. I'm still not sure exactly what issue you're actually facing. We need more details.

I successed to configure but failed to build the ASL in Ipopt. and the error massage was "cannot create regular file E:msys64homeIpopt/lib" . So I thougt the problem was the invalid path. And I want to reconfigure it. But I found the configure message that the install path still didn't change even though I changed the "--prefix" variable. So my question is how to modify the install path.By the way I tried to reappear the problem I faced another problem "The input file is specified twice".Please help me I have compiled it almost 4 days

**Comment by tkralphs** [comment] 2020-02-29 19:20
This could probably be resolved easily if you would just provide more relevant details, as requested. I still cannot tell what you're doing wrong exactly. I now finally understood that you are on Windows and it looks like you are using Msys. It also looks like you are passing Windows paths to `configure`, which is not going to work. You need to specify posix-style paths in MSys, so you would do something like
```
coinbrew build Ipopt --prefix=/e/home/Ipopt/
```
but I don't really know why you are specifying a prefix to begin with. Just build without specifying a prefix first to see if that works. If you just simply do
```
coinbrew build Ipopt
```
I would guess that will work. If not, provide the _exact_ command you typed and the **full** output. Also, please verify that my guesses about what you're doing are correct. We are trying to help, but you need to provide enough information for us to figure out what's happening.

**Comment by Timbersaw-wangzw** [comment] 2020-03-01 04:17
> This could probably be resolved easily if you would just provide more relevant details, as requested. I still cannot tell what you're doing wrong exactly. I now finally understood that you are on Windows and it looks like you are using Msys. It also looks like you are passing Windows paths to `configure`, which is not going to work. You need to specify posix-style paths in MSys, so you would do something like
> 
> ```
> coinbrew build Ipopt --prefix=/e/home/Ipopt/
> ```
> 
> but I don't really know why you are specifying a prefix to begin with. Just build without specifying a prefix first to see if that works. If you just simply do
> 
> ```
> coinbrew build Ipopt
> ```
> 
> I would guess that will work. If not, provide the _exact_ command you typed and the **full** output. Also, please verify that my guesses about what you're doing are correct. We are trying to help, but you need to provide enough information for us to figure out what's happening.

Thanks for your patiance. I encounter a new problem. 
$ ./coinbrew build Ipopt  --enable-msvc --no-prompt --build=x86_64-w64-mingw32                                          Welcome to the COIN-OR fetch and build utility

For help, run script with --help.

Package will be built in /f/PostgraduateStudy/Code/C++/Ipopt-3.12.13/coinbrew/coinbrew/build

################################################
### Building version master
### with existing versions of dependencies.
### Run 'fetch' first to switch versions
### or to ensure correct dependencies
################################################

输入文件指定了两次。(The input file is specified twice)
I reinstalled the coinbrew and msys and run the paman -Scc but the problem still exists. I am justing starting to use msys2.So there are some basic problems. Thanks a lot!!

**Comment by tkralphs** [comment] 2020-03-01 17:02
I don't know what the issue is. There are no errors in what you pasted except for possibly something in Chinese.

**Comment by tkralphs** [comment] 2020-03-01 17:18
There was a small bug in the version of `coinbrew` I checked in yesterday, which I just fixed. Perhaps this will fix the issue. Just be aware that if you're going to use Visual Studio to build Ipopt, you need to have the Visual Studio compiler in your path and you may also need the Intel Fortran compiler, depending on what linear solver you're using.

**Comment by tkralphs** [comment] 2020-03-01 17:28
You will also need to add `--tests=main` to avoid running the unit tests of the third party packages, since not all of them have unit tests.

**Comment by Timbersaw-wangzw** [comment] 2020-03-01 17:34
> Is this the entire output? I kind of doubt that it could be.

yes it is the entire output. the problem is "The input file is specified twice " and I just tried to add --tests=main. but the problem was the same.

**Comment by tkralphs** [comment] 2020-03-01 17:44
Installation is now done automatically following build and test of each project.

There should be some lines like this following the last line before the error.
```
Installation directory is writable.

Package will be installed to /home/tkral/coinbrew/dist

Caching configuration options...
--enable-msvc
--with-coin-instdir=/home/tkral/coinbrew/dist

##################################################
### Configuring ThirdParty/ASL 2.0
##################################################
...
```
If not, you don't have the latest version of `coinbrew` or something. Can you try with --verbosity=4 and send the *full* output.

**Comment by Timbersaw-wangzw** [comment] 2020-03-01 17:44
> There was a small bug in the version of `coinbrew` I checked in yesterday, which I just fixed. Perhaps this will fix the issue. Just be aware that if you're going to use Visual Studio to build Ipopt, you need to have the Visual Studio compiler in your path and you may also need the Intel Fortran compiler, depending on what linear solver you're using.

Ok thanks for your advices. The environment variable about inter and visual studio are set correctly. I am going to build the ipopt without coinbrew. Probably I will use coinbrew again until you fix the bug.

**Comment by tkralphs** [comment] 2020-03-01 17:48
The bug in `coinbrew` is fixed and I have now built Ipopt with Visual Studio in Msys on my own machine here using the same commands. Everything is working.

**Comment by svigerske** [comment] 2020-03-01 18:15
@tkralphs Let's close this.
We asked several times to get a full output (see my first reply), see the commands that was run, etc., without avail.

**Closed by svigerske** 2020-03-01 18:15 UTC
