### ISSUE TITLE
Problem building Ipopt with CoinBrew

### ISSUE THREAD

**Issue by smith-nekrald** [coin-or/coinbrew#84] opened 2023-04-27 21:37 UTC
Hi CoinBrew team,
Thank you for creating such a wonderful package manager.

When building Ipopt with coinbrew, the following lines appear before the process fails:
```

checking for package HSL... yes
checking for function ma27ad_ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function ma27ad in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function MA27AD_ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function MA27AD in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function ma27ad__ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function ma27ad_ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function MA27AD__ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
checking for function MA27AD_ in -L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl   ... no
configure: error: Provided package HSL is not working or does not contain MA27. See config.log for details on failed checks.

```

After studying config.log, I have found the following lines:
```
HSLLIB_CFLAGS='-I/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/include   -DHSLLIB_BUILD'
HSLLIB_CFLAGS_NOPC=' '
HSLLIB_LFLAGS='-L/home/jhogg/src/coinhsl/bin-linux_x86_64/coinhsl-linux-x86_64-2014.01.10/lib -lcoinhsl  '
HSLLIB_LFLAGS_NOPC=' '

```

Looks like HSL path is hardcoded, while the normal expectation is that HSL path is flexible (i.e. available through LD_LIBRARY_PATH or PATH environment variables). 

Please let me know if you want more information about the problem. OS Ubuntu Linux 22.04, recent update.

**Comment by svigerske** [comment] 2023-04-28 07:13
Closing as duplicate of coin-or/Ipopt#664 (and it better fits there)

**Closed by svigerske** 2023-04-28 07:13 UTC
